### ISSUE TITLE
KendoGrid - Can't use letter 'e' or number in grid data 

### ISSUE THREAD

**Issue by franzcatch** [kendo-labs/knockout-kendo#105]
The binding doesn't like when the data has an element that is named the letter 'e' or any number.

Works fine:  http://jsfiddle.net/qf2Qq/16/

"e is not a function":  http://jsfiddle.net/qf2Qq/17/

"Invalid template":  http://jsfiddle.net/qf2Qq/18/

**Comment by mishoo** [comment]
I can repro this without Knockout ([1](http://dojo.telerik.com/UsIro), [2](http://dojo.telerik.com/UsIro/2)), so I filed an internal ticket about this and I'm closing this one.
