### ISSUE TITLE
Knockout 3.0 compatibility

### ISSUE THREAD

**Issue by Trojaan** [kendo-labs/knockout-kendo#106]
Hi Ryan,

For a project I'm working on we are using your great library for the binding of the kendo components. Now I'm pretty exited about the new knockout 3.0 release! Since I read that it is intended to be fully backwards compatible, but has some major changes on how it's dealing with dependencies between bindings, I was wondering if you can tell me if this is compatible with the kendo-knockout lib. 

Keep up the good work!

**Comment by mishoo** [comment]
I assume this is no longer an issue, since we include knockout 3 in our repo.
