### ISSUE TITLE
kendoRangeSlider 100% width and disable tooltip

### ISSUE THREAD

**Issue by derekgguoctan** [kendo-labs/knockout-kendo#112]
Hi,

I have two questions here.

first, i would like to have my slider full fill the width (eg 100%). how?

second, i want to disable the tooltip. it does work, but the drag and drop behave strange. Any ideas?
http://jsfiddle.net/ULfR8/8/

thanks

**Comment by mishoo** [comment]
Adding `style="width: 100%"` — http://jsfiddle.net/ULfR8/8/
