### ISSUE TITLE
date picker not showing value

### ISSUE THREAD

**Issue by mmillican** [kendo-labs/knockout-kendo#129]
For some reason I can't get existing values to display in the kendo date picker.  The date format looks like `"2014-04-13T00:00:00"` (coming from .NET MVC action method).  I've tried a few different ways, the current being:

```
<input id="project-start-date" data-bind="kendoDatePicker: { value: StartOn, format: 'MM/dd/yyyy' } "/>
```

If I update the value on the UI, it does go back to the model.

Using latest version of Kendo and knockout-kendo.

**Comment by barfinup** [comment]
Did you guys identify what the actual problem was? I've got this exact issue - doesn't load the value, but does push back to the model. 
The JSfiddle also doesn't work anymore

Doesn't make any difference if I initialize the Date object or just do a mapping
