### ISSUE TITLE
Knockout-Kendo DataSource

### ISSUE THREAD

**Issue by ghost1face** [kendo-labs/knockout-kendo#132]
Hey,

Having troubles getting knockout/kendo to play nicely when using a datasource as the source data for a chart.  I am looking to use the group option.  Are there any plans for better datasource support?

**Comment by thelordgabo** [comment]
I have the same problem, this is the code: 
`<div data-bind="kendoGrid: gridConfig" id="grid">`

`public dataSource = new kendo.data.DataSource({
            //some config here
            transport: { },
            schema: { }
        });`

`public gridConfig = {
            data: this.dataSource,
            columns: [{
                field: "Discount",
                title: "Discount",
                width: "100px"
            }, {
                    command: ["edit"],
                    title: "&nbsp;",
                    width: "100px"
                },
                { command: ["destroy"] }],
            editable: {
                mode: "inline"
            }
        };`

and in the constructor:
`this.dataSource.sync();
 $('#grid').kendoGrid(this.gridConfig);`
