### ISSUE TITLE
KendoTreeView binding to something like kendo's observable array or observableHierarchy

### ISSUE THREAD

**Issue by bzamfir** [kendo-labs/knockout-kendo#139]
Hi,

Is it possible to data-bind a kendoUI treeview to knockout viewmodel using a data structure like observableHierarchy or an observableArray?

Is any example available? On http://rniemeyer.github.io/knockout-kendo/web/TreeView.html I found only some very basic examples related to treeview binding.

Thank you

**Comment by mishoo** [comment]
I added some code to handle the `data` argument similar to the Grid.  Here's an example: http://dojo.telerik.com/@mishoo/uSuzu

**Comment by bzamfir** [comment]
I tried to run the example, but it didn't work.

**Comment by mishoo** [comment]
Works for me in FF, but indeed not in Chrome.  Issue was loading the script directly from the raw Github address (missing proper content type header).  Here's fixed sample: http://dojo.telerik.com/@mishoo/uSuzu/2

**Comment by bzamfir** [comment]
Thanks. Is this build published as nuget package update yet, or should I get it directly from github?

**Comment by rniemeyer** [comment]
@bzamfir @mishoo - I can increment the version, rebuild, and publish to Nuget today.

**Comment by bzamfir** [comment]
Great, thanks.

2015-02-05 16:24 GMT+02:00 Ryan Niemeyer <notifications@github.com>:

**Comment by rniemeyer** [comment]
@bzamfir - `v0.9.2` is now in Nuget and Bower.

**Comment by bzamfir** [comment]
Is it possible to bind the treeview node to a template instead of text property of datasource?
Because I need to build a treeview as one shown below

![image](https://cloud.githubusercontent.com/assets/4658652/6063233/51c2d2cc-ad5e-11e4-8e05-9d81a77d945d.png)

The treeview shown above  was built using kendo hierarchical datasource, with a kendo template for nodes
```
<div id="dvPermitFilesK"
    data-role="treeview"
     data-drag-and-drop="false"
     data-checkboxes="{checkChildren: true, template: permitFiles_CheckBoxTemplate}"
     data-template= "ktmpl_PermitFiles"
     data-bind="source: Files,
                events: { select: onFileSelect }">
</div>
```

**Comment by bzamfir** [comment]
The data-bound kendo treeview no longer works in either latest Chrome (Version 43.0.2357.130 m) or FF (38.0.5)
I appreciate if you can provide a fix.

Thank you
