### ISSUE TITLE
change event fired twice

### ISSUE THREAD

**Issue by nrso** [kendo-labs/knockout-kendo#145]
Hi,

I'm having an issue with the kendoDatePicker.

Here is the code: http://jsfiddle.net/5VGCK/192/

When i select the value with the calendar everything goes fine, but when i change it by hand directly in the input the change event is called twice
The first call is with the old value, and the second one with the new value

Any idea why ?

**Comment by mishoo** [comment]
This appears to be a Kendo UI issue, logged here: https://github.com/telerik/kendo-ui-core/issues/532
