### ISSUE TITLE
Grid sorting not working properly with grid KO templates while grid resizes

### ISSUE THREAD

**Issue by Sivanraj-M** [kendo-labs/knockout-kendo#154]
Hi,
I have a kendo grid that uses knockout row template and i have enabled sorting and resize in that grid,
It is working fine when i do sorting and resizing as separately,
but when I'am resize the last column i got the scroll bar, now scroll to right end and try to sort the last column sorting is working but scroll bar is automatically come to left. 

here i have JSFiddle example - http://jsfiddle.net/SivanRaj/p5LL8o7r/4/

try to execute the below steps you can reproduce the issue.

1) resize the last column,
2) scroll to right.
3) sort last column now scroll bar is automatically come to left.

please anyone help me with this issue.

Thanks
Sivanraj

**Comment by mishoo** [comment]
You must include the row UID, [as documented](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-rowTemplate) (add `data-uid="#: uid #"` to the `<tr>`).  This way it works properly: http://jsfiddle.net/SivanRaj/p5LL8o7r/4/
