### ISSUE TITLE
Grid filtering & sorting no working when used row templates

### ISSUE THREAD

**Issue by rasin8** [kendo-labs/knockout-kendo#156]
Hi Team,
We are using Kendo Grid with Knockout framework.
Filtering and Sorting functionalities does not work when we bind with Knockout.
We are using rowtemplate to achieve our requirements. There does not seem to be any integration issues and other functionalities work as expected.

/RAM

**Comment by mishoo** [comment]
Works for me.  If you can still see the problem please [provide a sample](http://dojo.telerik.com/).
