### ISSUE TITLE
Dropdownlist returns strings instead of numbers

### ISSUE THREAD

**Issue by michaelaird** [kendo-labs/knockout-kendo#167]
When binding a dropdownlist using DataTextField and DataValueField where DataValueField is a number, the dropdownlist always returns strings for the selected value.

See this jsFiddle for a repro: http://jsfiddle.net/vghhqhp7/1/

I'm not sure if this is a Kendo issue or a knockout-kendo issue...

**Comment by mishoo** [comment]
It's a Kendo issue.  The [_accessor()](https://github.com/telerik/kendo-ui-core/blob/7de62e52d89621406c07b97bf8fd809aafa257b9/src/kendo.list.js#L689) method, which ends up being used by the dropdown to report the widget's value, returns the value of the `<select>` element, which is always a string.
