### ISSUE TITLE
Treeview databinding issue in 0.9.2

### ISSUE THREAD

**Issue by AlicePain** [kendo-labs/knockout-kendo#171]
Version 0.8.1 would bind a knockout observablearray to the TreeView dataSource and display correctly.  The latest version throws an e.slice error.  

the HTML looks like this
 
![code](https://cloud.githubusercontent.com/assets/11410512/6579242/6a0bf504-c71f-11e4-9f6b-48168744905f.png)

People object contains text and items.

I think the issue is in the defaultOption: DATA   this code wasn't in 0.8.1.  Not sure when it was added.

**Comment by Nedlinin** [comment]
:thumbsup:

Same issue here.

**Comment by steveba14** [comment]
and here.

**Comment by AlicePain** [comment]
I tried a number of options to get this working and couldn't, ended up modifying the code to get it back to 0.8.1.   Just make the following change and then re-minify.
createBinding({
    name: "kendoTreeView",
    async: true
});

//createBinding({
//    name: "kendoTreeView",
//    defaultOption: DATA,
//    watch: {
//        data: function(value, options) {
//            ko.kendo.setDataSource(this, value, options);
//        }
//    },
//    events: {
//        change: function(options, e) {
//            if (ko.isWriteableObservable(options.value)) {
//                var tree = e.sender;
//                options.value(tree.dataItem(tree.select()));
//            }
//        }
//    },
//    async: true
//});

**Comment by rniemeyer** [comment]
@AlicePain, @Nedlinin, @steveba14 - Just released v0.9.3 that removes the `defaultOption` for TreeView. This also allows TreeViews that use DOM nodes rather than data to function again.

**Comment by golgote** [comment]
@rniemeyer I have the same problem with the kendoListView binding. Removing ```defaultOption``` fixes it for me as well.
