### ISSUE TITLE
Kendo DropDownList is holding on to old observable

### ISSUE THREAD

**Issue by IanYates** [kendo-labs/knockout-kendo#182]
I've created a fiddle

https://jsfiddle.net/a8f1kynp/6/

Gross simplification but it gets the point across..  Apologies for my complete lack of CSS awesomeness.

Basically I have 2x objects in my view model - ref1 & ref2.  There's an activeRefIndex observable on my view model to control which ref object is the focus of the user's attention.  I've added a function toggleRefIndex to toggle between ref1 & ref2 being active.

ref1 and ref2 each have a single field (in our app they'd have many like name, address and phone number, but that's not important here) and that single field is itself an observable  (in our app we're using KO ES5, but that's not necessary to reproduce the problem fortunately).  In the fiddle, that single field is called `selectedChoice` and lets the user choose a fruit.

ref1 starts off with apple (value = 1) and ref2 starts off with banana (value = 2).

There's a regular ko.computed to expose either ref1 or ref2 based on the activeRefIndex.  This computed is called activeRef.  We start off with ref1 being active.

So I have a regular <select> list bound via Knockout's options binding, plus a KendoDropDownList as well.  They're each bound to activeRef().selectedChoice.

The regular <select> element behaves properly.  It notices the change to activeRef and rebinds to the new selectedChoice observable from the activeRef.
The Kendo dropdown does not behave properly.  It wires up binding to ref1's selectedChoice observable.  Great.  But then if activeRefIndex is set to 2, the Kendo dropdown is STILL bound to ref1's selectedChoice

I added some logging to appear at the bottom of the HTML output that really makes the problem clear...
Steps to reproduce
* Change the Kendo dropdown's value away from Apple to Grape - the <select> changes too as you'd expect.  Ref 1's value also updates.
* Hit "toggle ref index"
* The <select> changes to banana, as it should.  The Kendo dropdown stays showing grape, which is ref 1's value.  Frankly I could stop the repo steps here, but here's some more to push the point home

* Change the kendo dropdown's selection from grape to orange
* You'll see in the log that ref1 changed.  It should have been ref2.
* Change the select's selection from banana to apple
* You'll see in the log that ref2 changed, which is correct.  The Kendo dropdown is unaffected, which is incorrect.

I've worked around it by wrapping the Kendo components in with: bindings of the form
<div data-bind="with:activeRef">   <<<<kendo code>>>>>   </div>

**Comment by IanYates** [comment]
Yuk - forgot to preview :)

At the end, I'm just trying to say I can wrap the Kendo components in a div and data-bind=with:activeRef

The problem with this is that it's quite insidious.  If the only display is via the Kendo UI component, it's really not obvious that the problem even exists except when you go to save and realise what was on the screen is NOT what is being sent to the server :(

**Comment by IanYates** [comment]
Any thoughts on this?

Would it help if the kendoDropDownList binding was coded more like the options binding in Knockout, where instead of one binding of the form
`kendoDropDownList: {   complexObject   }`
we would have

`kendoDropDownList: dataSource, kendoDropDownListDataTextField: 'textField', kendoDropDownListDataValueField: 'valueField", value: myObservable`

I remember some similar discussion on the KO discussion forum (or perhaps the issues tracker?) where this would make a difference as to how often init/update was called on the binding when the observables changed.  That makes some sense, as valueAccessor can only know about the `complexObject`, which happens to contain some observables, rather than knowing about an observable value directly.
Having said all of that, the ko-kendo binding handler can (and does, I believe) subscribe to the inner observables anyway...

I'm happy to sink some effort in to solve this but I'd like some pointers from those with a bit more under the covers knowledge about Knockout and/or Kendo if possible.

**Comment by rniemeyer** [comment]
@IanYates - Sorry for the super, super delayed response. This one is an issue related back to how the binding is setup using computeds in the `init` function. In KO 3+, the actual code is parsed in a way that it does not run until the valueAccessor() arg to a binding is called (or from allBindingsAccessor). Knockout-Kendo would need to find someway to pass the valueAccessor along to the event handlers and computeds for updating the view. Discussed some in #174.

For your particular issue here, if you can avoid accessing an observable in the binding string (`activeRef().selectedChoice`), then it will work. Here is a solution using a writeable computed: https://jsfiddle.net/rniemeyer/k367aayv/ . I don't think it is ideal to have to do that, just pointing it out for the sake of a workaround.

I think that the changes to improve this situation would be quite helpful, but will be pretty intrusive. I will certainly consider tackling it when I have a chance. 

Sorry again for the delayed response.

**Comment by IanYates** [comment]
@rniemeyer - thanks for the reply.  No problem with the delay - I know you're plenty busy! :)

What you've said makes sense.  Thanks for the link to the other thread where this was spelt out more clearly & succinctly than what I wrote here. In particular, the part about valueAccessor's evaluation making it impossible to split apart the difference between something and somethingElse's dependencies.

The writable computed is a good workaround.  The behaviour is unfortunate as things can, to the uninitiated, look like they're working, but I can explain it to others in the team well enough - it needs an observable to bind to rather than an expression to evaluate (which then may return an observable).
