### ISSUE TITLE
hasFocus for text input in Kendo window

### ISSUE THREAD

**Issue by elisheva50** [kendo-labs/knockout-kendo#188]
I am working on a project and I have a Kendo window that opens up and shows a textbox. I want the focus to be in the textbox when the window is opened so the user can start typing right away. I created an example in JSFiddle: http://jsfiddle.net/elisheva50/xu8d660p/. 

I have tried several binding handler examples that I found, including one from another knockout-kendo issue:

https://github.com/kendo-labs/knockout-kendo/issues/78

and this one:

http://jsfiddle.net/mbest/tAGmp/

I also tried various usages of "hasFocus" (for both the kendoWindow div and the input div), either set to isOpen or true. Then I added the autoFocus field for kendoWindow. 

So far, no luck! Any ideas? Thanks!

**Comment by rniemeyer** [comment]
@elisheva50 - sorry for the delayed response. If you are still having this issue, then one approach is to add a handler to the `activate` event (which is triggered when the open animation is done). The handler can set an observable to true and you can bind your input using `hasFocus` against that observable.

Here is a sample: http://jsfiddle.net/rniemeyer/4eqLhsbf/

In my sample, I bound the observable as a handler directly forcing the observable to true like `activate: focusInput.bind(null, true);`

Hope that helps!

**Comment by elisheva50** [comment]
Thanks, I moved on to other parts of the project, so the delay wasn't a problem. I am going to give this a try when I have a chance!

**Comment by elisheva50** [comment]
I finally got the chance to implement this today and it worked on the first try! I have the window and the textbox in separate components, so I had to use postbox to get the focusInput value from one to the other, but that worked fine. Thanks for your help!
