### ISSUE TITLE
Allowing for KeyUp binding for KendoEditor

### ISSUE THREAD

**Issue by DaveStonge** [kendo-labs/knockout-kendo#191]
I noticed that the only binding is Change and that KeyUp or some form of option for it is not included. Is this something you avoided due to performance constraints? If so, I was wondering if there was some form of throttling that could be done to not overload the binding with updates.

**Comment by rniemeyer** [comment]
I would be a bit worried about performance. As a workaround, here is an example of how you can turn this functionality on for yourself:

```html
<textarea data-bind="kendoEditor: { value: content, keyup: handler }" ></textarea>
```

```js
var ViewModel = function() {
   this.content = ko.observable("this is a <strong>test</strong>!");
   this.handler = function(e) {
        this.content(e.sender.value());
   }.bind(this);
};
```

Here is a running sample: http://jsfiddle.net/rniemeyer/thc1pn4r/

Hope this helps!
