### ISSUE TITLE
Widget disposal not working as intended

### ISSUE THREAD

**Issue by three88bu** [kendo-labs/knockout-kendo#192]
There seems to be an issue with disposal of widgets in certain cases. For example, if I place a dropdown in a grid and then switch pages, the dropdowns are not cleaned up properly. Here is a fiddle: http://jsfiddle.net/three88bu/6gu5n5h2/

if (widget.destroy) {
                ko.utils.domNodeDisposal.addDisposeCallback(element, function() {
                    if (widget.element) {
                        if (typeof kendo.destroy === "function") {
                            kendo.destroy(widget);
                        } else {
                            widget.destroy();
                        }
                    }
                });
            }

Was the intention for line 5 the following?

kendo.destroy(widget.element);

**Comment by rniemeyer** [comment]
@three88bu - definitely looks like you are correct

**Comment by three88bu** [comment]
@rniemeyer - Cool. I made a meager attempt at creating a pull request, but im a github noob so that didnt go too far. Probably not worth trying to figure out for such a minor change anyway.

Thanks!

**Comment by rniemeyer** [comment]
I'll fix it up this weekend. Feel free to try a PR, if you want to learn/try. Happy to help you through it or clean it up.

**Comment by three88bu** [comment]
I will probably take another stab at it when I have a bit more time. Its time to learn it I think.

As always, thanks a bunch for the support!

**Comment by rniemeyer** [comment]
@three88bu - I took care of this one. If there you ever want to submit another PR and need help, just let me know. Thanks!

**Comment by dkrmer88** [comment]
There might be another problem with the widget disposal because I am currently experiencing a big memory leak because of dataStore objects being referenced in DOM elements associated with kendo controls.

I had to manually call **ko.utils.domData.clear** on all dom nodes referenced by the widget so that I ended up doing ugly things like:

```javascript
if (widget.element) {
    for (var key in widget) {
        if (widget[key] instanceof jQuery && widget[key].length > 0) {
            ko.utils.domData.clear(widget[key][0]);
        }
    }

    if (typeof kendo.destroy === "function") {
        kendo.destroy(widget.element);
    } else {
        widget.destroy();
    }                            
}
```

After I removed these references the garbage collector could clean up those unneeded dom elements.
@rniemeyer can you confirm that this is a problem?

Thanks!
