### ISSUE TITLE
using the 'valueUpdate' binding along with the kendoEditor

### ISSUE THREAD

**Issue by scummins-caci** [kendo-labs/knockout-kendo#198]
Is it possible to use the 'valueUpdate' binding with the kendoEditor control?  I am trying to get a character count and used valueUpdate: afterkeydown on a regular textarea, but when I added the kendoEditor binding it doesn't work anymore.

**Comment by rniemeyer** [comment]
@scummins-caci - `valueUpdate` does not work with the kendoEditor, but you can attach to the `keyup` event like this: http://jsfiddle.net/rniemeyer/thc1pn4r/

Hope that helps!

**Comment by scummins-caci** [comment]
Thanks!
