### ISSUE TITLE
Kendo grid change is not reflected in viewmodel

### ISSUE THREAD

**Issue by Nadynho** [kendo-labs/knockout-kendo#200]
Hello,

I've managed to populate a grid with observablearray(of observables), when I change the value of one instance from the view model, its reflected within the grid (on the UI). My problem is that, when I change the value from the grid, the view model is not updated. Is this how the knockout-kendo works? Or am I doing something wrong while configuring the grid?

Its not a big issue to fix the syncronization, I can update the view model using the OnChange event handler provided by the kendo datasource, but, do I need to do it myself or is this already implemented?

Thank you very much,
Bogdan.

**Comment by rniemeyer** [comment]
Edits made in the grid are not automatically synced back to the original data, except when you are using the `useKOTemplates` option to make a cell/row a Knockout template.
