### ISSUE TITLE
MultiSelect: select by typing and hitting Enter erases previous values

### ISSUE THREAD

**Issue by bmsmg** [kendo-labs/knockout-kendo#202]
Noticed this in 2015.1.x.  If you select one or more values in a multiselect, then select another value by typing the first few letter of the name and hitting Enter to select it, the previously selected items no longer appear in the multiselect (though they still exist in the underlying observable array in my tests):

http://jsfiddle.net/mgrant/eeu5Ls8m/2/

Simple Kendo-only example works:

http://jsfiddle.net/mgrant/gbLke5c1/

**Comment by bmsmg** [comment]
The problem arises from the dataSource being filtered as you type.  When knockout-kendo tries to set the value, the value indices of the previously selected items no longer exist in the view, so only the currently selected item is displayed.  Working on a fix...

**Comment by rniemeyer** [comment]
Added a change in 0.9.6 to clear the filter on a value change, which in my testing fixes issues with both selecting new values and programmatically setting the value(s) to something new. Thanks!
