### ISSUE TITLE
Exception thrown in knockout.js while deleting item from kendo scheduler

### ISSUE THREAD

**Issue by BreakTheSilence** [kendo-labs/knockout-kendo#228]
Exception thrown in knockout.js: Uncaught TypeError: Cannot read property 'length' of undefined while trying to remove item from kendo scheduler.

Demo: http://dojo.telerik.com/uyIFI

Currently, I'm trying to figure out the problem.

**Comment by rniemeyer** [comment]
Fixed in v0.9.7
