### ISSUE TITLE
Validation of kendoui-widgets

### ISSUE THREAD

**Issue by fbuchinger** [kendo-labs/knockout-kendo#25]
I use a lot of kendo ui widgets in my forms, knockout-kendo is responsible for the model-binding. today i tried to integrate knockout-validation, but i struggled so far. Validation messages are displayed twice for each kendo ui widget with an error, I have to select/enter a value twice to remove the messages.

Any hints how i can integrate validation into knockout-kendo?

**Comment by safouenmzah** [comment]
Gents,
I am unable to get it working for a simple drop down list.
Any suggestions?
Thanks

**Comment by safouenmzah** [comment]
Hi,
This is a fiddle "not working" for a simple drop down list
http://jsfiddle.net/rniemeyer/h9JKx/#&togetherjs=wStwvKFIPy

Thanks!

**Comment by IanYates** [comment]
Hi @safouenmzah - that fiddle link takes me to a date picker, not a drop down list.  Can you try to make a fiddle again?
