### ISSUE TITLE
Allow Datasource to be defined in kendoGrid options

### ISSUE THREAD

**Issue by CraigHead** [kendo-labs/knockout-kendo#58]
Currently setting the dataSource option in the kendoGrid doesn't not affect the data displayed. 

For example 'date' or 'number' data in the observable collection should be able to be parsed by the 'format' specified in the columns definition. 

```
         <div id="grid" data-bind="kendoGrid: { 
                            data: SaleSearchResults,
                            dataSource: {
                                schema: {
                                    model: {
                                        fields: {
                                            PropertyType: { type: 'string' },
                                            ActualCapRate: { type: 'number' },
                                            SaleDate: { type: 'date' },
                                            PricePerSF: { type: 'number' }
                                        }
                                    }
                                }
                            },
                            groupable: true,
                            sortable: true,
                            selectable: 'multiple',
                            pageable: {
                                pageSizes: true
                            },
                           columns: [

                            {
                                field: 'PropertyType',
                                width: 120,
                                title: 'Property Type'
                            },
                            {
                                field: 'ActualCapRate',
                                width: 90,
                                title: 'Actual CapRate'
                            },
                            {
                                width: 120,
                                format: '{0:MM/dd/yyyy}',
                                field: 'SaleDate',
                                title: 'Sale Date'
                            },
                            {
                                width: 120,
                                field: 'PricePerSF',
                                format: '{0:c}',
                                title: 'Price Per Square Foot'
                            }
                            ]}">
```

BTW there was SO entry regarding this issue. 
http://stackoverflow.com/questions/13935484/kendo-knockout-use-knockout-view-model-with-kendo-datasource

**Comment by kmagilavy** [comment]
I was able to get this to work by setting data to null in the configuration options.

     <div data-bind="kendoGrid: { 
          data: null,
          dataSource: {
               transport: {
                    read: {
                            dataType: 'json',
                            url: '/api/example'
                    }
               }
          }
     }

Only when settings that data options to null does it actually reach out to the server and work for me.

**Comment by fpstidston** [comment]
> http://jsfiddle.net/rniemeyer/FpKM2/

This produces an error after it draws preventing other knockout from rendering on the page - can't find length of null.

**Comment by bmsmg** [comment]
I think the error you're seeing is due to providing both 'data' and 'dataSource'.  According to ko-kendo docs, it expects 'data' to be either an array, observable array, or a dataSource.  I have modified your sample a bit: http://jsfiddle.net/urawk2p8/
I prefer to keep the bindings in the model instead of making the HTML more verbose, but otherwise the only difference is the creation of the dataSource and using the 'data' property.

**Comment by CraigHead** [comment]
Closing issue. This issue was opened 6 years ago and this issue isn't important to me anymore.
